basal/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView
from . import views

urlpatterns = patterns('',
    url(r'^$', views.MainView.as_view(), name='main'), 
    url(r'^about_us/$', 
        TemplateView.as_view(template_name="basal/aboutus.html"),
        name='about_us'),
    url(r'^registration/$', views.RegistrationView.as_view(), 
        name='registration'),
    url(r'^login/$', 
        'django.contrib.auth.views.login', {
            'template_name': 'basal/login.html'},
        name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', {
            'template_name': 'basal/password_reset.html',
            'email_template_name': 'basal/password_reset_email.html',
            'post_reset_redirect': '/courses/'}, 
        name='password_reset'),
    url(r'^password_reset_confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 
        'django.contrib.auth.views.password_reset_confirm', {
            'template_name': 'basal/password_reset_confirm.html',
            'post_reset_redirect': '/courses/'},
        name='password_reset_confirm'),
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'), 
    url(r'^dashboard/password_change/$', 
        'django.contrib.auth.views.password_change', {
            'template_name': 'basal/password_change.html',
            'post_change_redirect': '/dashboard/'},
        name='password_change'),
    url(r'^dashboard/profile_update/$', views.ProfileUpdateView.as_view(),
        name='profile_update'),
)

courses/urls.py
from django.conf.urls import patterns, url
from . import views
from django.views.generic import TemplateView
from django.views.decorators.csrf import csrf_exempt

urlpatterns = patterns('',
    url(r'^$', views.CourseIndexView.as_view(), name='course_index'),
    url(r'^(?P<course>\w+)/$', views.LessonIndexView.as_view(), 
        name='lesson_index'),
    url(r'^(?P<course>\w+)/end_of_course/$', 
        views.EndOfCourseView.as_view(), name='end_of_course'),
    url(r'^(?P<course>\w+)/lesson_(?P<l_no>\d+)/$', 
        views.LessonView.as_view(), name='lesson'),
    url(r'^(?P<course>\w+)/lesson_(?P<l_no>\d+)/challenge_(?P<c_no>\d+)/$', 
        views.ChallengeView.as_view(), name='challenge'),
    
)

script_cafe/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('basal.urls', namespace='basal')), 
    url(r'^admin/', include(admin.site.urls)),
    url(r'^courses/', include('courses.urls', 
        namespace='courses')),
)

courses/models.py
from django.db import models
from basal.models import *
from django.contrib.auth.models import User

class Course(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    short_description = models.TextField()
    long_description = models.TextField()
    summary = models.TextField()

    def __unicode__(self):
        return u'[%s Course]' % str(self.title)

    def get_total_challenges(self):
        return Challenge.objects.filter(lesson_id__course_id=self.id).count()

class Lesson(models.Model):
    title = models.CharField(max_length= 100)
    no = models.SmallIntegerField()
    description = models.TextField()
    course_id = models.ForeignKey(Course)
    video_link = models.URLField()

    def __unicode__(self):
        return u'%s[Lesson %s]' % (str(self.course_id), str(self.no))

    def get_all_challenge(self):
        return Challenge.objects.filter(lesson_id=self.id)

class Challenge(models.Model):
    NEXT_URL_CHOICES = (
        ('next_challenge', 'Next Challenge'),
        ('next_lesson', 'Next Lesson'),
        ('end_of_course', 'End of Course'),
    )
    lesson_id = models.ForeignKey(Lesson)
    title = models.CharField(max_length=100)
    no = models.SmallIntegerField()
    description = models.TextField()
    snippet = models.TextField()
    answer_snippet = models.TextField()
    next_url = models.CharField(max_length=20,
                                choices=NEXT_URL_CHOICES,
                                default='next_challenge')

    def __unicode__(self):
        return u'%s[Challenge %s: %s]' %  (self.lesson_id, 
                                          str(self.no), self.title)

    def get_course(self):
        return self.lesson_id.course_id.title

class SupportCode(models.Model):
    CODE_TYPE_CHOICES = (
        ('html', 'HTML'),
    )
    type = models.CharField(max_length=10,
                            choices=CODE_TYPE_CHOICES,
                            default='html')
    challenge_id = models.ForeignKey(Challenge)
    snippet = models.TextField()

    def __unicode__(self):
        return u'%s [Support %s]' % (str(self.challenge_id), str(self.type))

class Instruction(models.Model):
    description = models.TextField()
    challenge_id = models.ForeignKey(Challenge)

    def __unicode__(self):
        return u'%s [Instruction %s]' % (str(self.challenge_id), str(self.id))

class Hint(models.Model):
    description = models.TextField()
    challenge_id = models.ForeignKey(Challenge)

    def __unicode__(self):
        return u'%s [Hint %s]' % (str(self.challenge_id), str(self.id))

courses/views.py
from django.utils import timezone
from django.views import generic
from .models import *
from basal.models import *
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required 
from django.views.decorators.csrf import ensure_csrf_cookie
#from django.utils import timezone
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseServerError
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render_to_response

class CourseIndexView(generic.TemplateView):
    template_name = 'courses/course_index.html'

    def get_context_data(self, **kwargs):
        context = super(CourseIndexView, self).get_context_data(**kwargs)
        temp = Course.objects.all()
        context['course_list'] = {}

        for i in range(0, temp.count()):
#            import pdb;pdb.set_trace()
            current_user = UserProfile.objects.get(user_id=self.request.user) 

            context['course_list'][temp[i].slug] = {
                    'title': temp[i].title,
                    'short_description': temp[i].short_description,
                    'slug': temp[i].slug,
                    'completed': current_user.completed_course(temp[i].slug)}

        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CourseIndexView, self).dispatch(*args, **kwargs)

class LessonIndexView(generic.TemplateView):
    template_name = 'courses/lesson_index.html'

    def get_queryset(self):
        return Lesson.objects.filter(course_id__slug=self.kwargs['course']) 

    def get_context_data(self, **kwargs):
        context = super(LessonIndexView, self).get_context_data(**kwargs)

        current_user = UserProfile.objects.get(user_id=self.request.user)
        l_set = Lesson.objects.filter(course_id__slug=self.kwargs['course']) 

        context['course'] = self.kwargs['course'] 
        context['lesson_list'] = {}

        for i in range(0, l_set.count()):
            context['lesson_list'][l_set[i].no] = {
                       'title': l_set[i].title,
                          'no': l_set[i].no,
                 'description': l_set[i].description,
                  'challenges': {}
            }

            current = context['lesson_list'][l_set[i].no]['challenges']

            c_set = l_set[i].get_all_challenge()

            for j in range(0, c_set.count()):
                temp = current_user.completed_challenge(c_set[j].id)
      #          import pdb;pdb.set_trace()
                
                current[c_set[j].no]= {
                        'title': c_set[j].title,
                           'no': c_set[j].no,
                    'completed':  temp
                }

        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LessonIndexView, self).dispatch(*args, **kwargs)

class LessonView(generic.TemplateView):
    template_name = 'courses/lesson.html'

    def get_context_data(self, **kwargs):
#        import pdb;pdb.set_trace()
        context = super(LessonView, self).get_context_data(**kwargs)
        temp = Lesson.objects.filter(course_id__slug=self.kwargs['course'])
        context['lesson'] = temp.get(no=self.kwargs['l_no'])
        context['course'] = Course.objects.get(slug=self.kwargs['course'])
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LessonView, self).dispatch(*args, **kwargs)


class ChallengeView(generic.UpdateView):
    template_name = 'courses/challenge.html'

    def get_object(self):
        course = self.kwargs['course']

        user = User.objects.get(id=self.request.user.id)
        temp = Challenge.objects.filter(lesson_id__course_id__slug=course)
        temp = temp.filter(lesson_id__no=self.kwargs['l_no'])

#        import pdb;pdb.set_trace()
        challenge = temp.get(no=self.kwargs['c_no'])

        try:
            temp = ChallengeProgress.objects.filter(user_id=user.id)
            challenge_progress = temp.get(challenge_id=challenge.id)

        except ChallengeProgress.DoesNotExist:
            challenge_progress = ChallengeProgress(challenge_id=challenge,
                                             user_id=user,
                                             snippet=challenge.snippet)
            challenge_progress.save()
        return challenge_progress

    def get_context_data(self, **kwargs):
        context = super(ChallengeView, self).get_context_data(**kwargs)

        course = self.kwargs['course']
        temp = Challenge.objects.filter(lesson_id__course_id__slug=course)
        temp = temp.filter(lesson_id__no=self.kwargs['l_no'])

        context['challenge'] = temp.get(no=self.kwargs['c_no'])
        context['course'] = Course.objects.get(slug=self.kwargs['course'])
        context['l_no'] = self.kwargs['l_no']

        user = UserProfile.objects.get(user=self.request.user)
        context['the_user'] = user
        return context

    def post(self, request, *args, **kwargs):
        user = User.objects.get(id=self.request.user.id)
        course = self.kwargs['course']
        temp = Challenge.objects.filter(lesson_id__course_id__slug=course)
        temp = temp.filter(lesson_id__no=self.kwargs['l_no'])
        challenge = temp.get(no=self.kwargs['c_no'])

        try:
            temp = ChallengeProgress.objects.filter(user_id=user.id)
            challenge_progress = temp.get(challenge_id=challenge.id)
            challenge_progress.snippet = request.body
            challenge_progress.completed_date = timezone.now()

        except ChallengeProgress.DoesNotExist:
            challenge_progress = ChallengeProgress(challenge_id=challenge,
                                            user_id=user,
                                            snippet=request.body,
                                            completed_date=timezone.now())
        
        challenge_progress.save()

#        import pdb;pdb.set_trace()
        if challenge.next_url == 'next_challenge':
            message = "Well done! Let's move on to the next challenge"
            button_val = 'Next Challenge'
            next_url = reverse('courses:challenge', kwargs={
                'course': kwargs['course'],
                'l_no': kwargs['l_no'],
                    'c_no': int(kwargs['c_no']) + 1})
            
        elif challenge.next_url == 'next_lesson':
            message = "Well done! You have completed this lesson. Let's " \
                      "move on to the next lesson"
            button_val = 'Next Lesson'
            next_url = reverse('courses:challenge', kwargs={
                'course': kwargs['course'],
                'l_no': int(kwargs['l_no']) + 1,
                    'c_no': 1})

        else :
            message = 'Congratulations, You have completed the course!'
            button_val = 'End of Course'
            next_url = reverse('courses:end_of_course', kwargs={
                'course': kwargs['course']})

        return render_to_response('courses/success_snippet.html', {
               'message': message,
            'button_val': button_val,
              'next_url': next_url 
        })

    @method_decorator(login_required)
    @method_decorator(ensure_csrf_cookie)
    def dispatch(self, *args, **kwargs):
        return super(ChallengeView, self).dispatch(*args, **kwargs)

class EndOfCourseView(generic.DetailView):
    template_name = 'courses/end_of_course.html'
    context_object_name = 'course'

    def get_object(self):
        return Course.objects.get(slug=self.kwargs['course'])

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(EndOfCourseView, self).dispatch(*args, **kwargs)

courses/templates/courses/challenge.html
{% extends 'base_2.html' %}

{% block title %}{{ challenge.lesson_id.course_id.title }}:  
{{ challenge.lesson_id.title }}: {{ challenge.title }}
{% endblock %}

{% block extra_script_link %}
{% load staticfiles %}
<script type='text/javascript' 
    src='{% static "courses/codemirror/codemirror-compressed.js" %}'></script>
<link rel="stylesheet" type='text/css' 
href='{% static "courses/codemirror/codemirror.css" %}' />
<link rel="stylesheet" type='text/css' 
href='{% static "courses/codemirror/mbo.css" %}' />

<script type='text/javascript' 
    src='{% static "courses/html_challenge_validator.js" %}'></script>
<script type='text/javascript' 
    src='{% static "courses/challenge.js" %}'></script>
<link rel='stylesheet' type='text/css' 
href='{% static "courses/challenge.css" %}' />



{% endblock %}

{% block body %}
<div id="user_preview">
    <div class='tutorial' id="tutorial_4">
        <p>This window will give you an idea of what your html code will look like on an actual browser.</p>
    </div>

    <div id='user_preview_content'></div>
    <!--    <span id='fullscreen_btn'>Full Screen</span>--!>
    <span id='minimize_btn'>Minimize</span>
</div>

<div id='left_wrapper'>
    
    <div id='top_left_wrapper'>
        <div id='nav_wrapper'>
            <nav>
            <h3>MENU</h3>
            <a class='links' href='{% url "courses:course_index" %}'>
                <div class='link_div'>COURSES</div></a>
            <a class='links' href='{% url "courses:lesson_index" course.slug %}'>
                <div class='link_div'>LESSONS</div></a>

            {% if user.username %}
            <a class='links' href='{% url "patio:dashboard" %}'>
                <div class='link_div'>DASHBOARD</div></a>
            <a class='links' href='{% url "patio:logout" %}'>
                <div class='link_div'>LOGOUT</div></a>
            {% else %}
            <a class='links' ><div class='link_div'
                    data-url='{% url "patio:login" %}'>LOGIN</div></a>
            <a class='links' ><div class='link_div' 
                    data-url='{% url "patio:registration" %}'>
                    REGISTER AN ACCOUNT</div></a>
            {% endif %}
            </nav>
        </div>
    </div>

    <div id='left_top_wrapper'>
        <img id='expand_btn' height='30' 
        src='{% static "strip_button.gif" %}' alt='expand btn' />
        <span>{{ course.title }}</span>
    </div>

    <div id='left_center_wrapper'>
        <div id='description_wrapper'>
<div class='tutorial' id="tutorial_1">
    <p>This is the description area, besides the video, this should remind you of what you have just learned</p> 

    </div>

            <h1>{{ challenge.lesson_id.title }}</h1> 
            <h2>{{ challenge.no }}. {{ challenge.title }}</h2>
            <p>{{ challenge.description|safe }}</p>
        </div>
        <div id='instruction_wrapper'>
<div class='tutorial' id="tutorial_2">
    <p>A detail instruction of what you are suppose to achieve will be suggested in this section</p>
    </div>

            <h4>Instructions</h4>
            {% for instruction in challenge.instruction_set.all %}
            <p>{{ instruction.description|safe }}</p>
            {% endfor %}
        </div>
        <div id='hint_btn'>Have trouble? Click me to reveal hint.</div>
        <div id='hint_wrapper'>
            {% for hint in challenge.hint_set.all %}
            <p>{{ hint.description|safe }}</p[>
            {% endfor %}

        </div>
    </div>

    <div id='left_footer_wrapper'>
    </div>
</div>

<div id='right_wrapper'>
        <div class='tutorial' id="tutorial_3">
            <p>Key in your input here</p>
    </div>

    <div id='user_input_tab'><span>challenge0{{ challenge.no }}.
            {{ course.slug }}</span></div>
    <div id='user_input_wrapper'
        data-url='{% url "courses:challenge" course.slug l_no challenge.no %}'
        data-validating_info='{{ course.slug }}'
        data-answer_snippet='{{ challenge.answer_snippet }}'
        data-new_user={{ the_user.new_user }}
        data-original_snippet='{{ challenge.snippet }}'>
        {{ form.snippet }}
    </div>

    <div id='right_footer_wrapper'>
    <div class='tutorial' id="tutorial_5">
        <p>When you are all done, submit and check if you are right</p>
    </div>

        <span id='save_submit_btn'>Save and Submit</span>
        <span id='reset_btn'>Reset Code</span>
    </div>

    <div id='success_result_container'>
        <div>&#10003;</div>
        <div id='success_result_message'></div> 
        <div id='close_success_btn'>&#215;</div>
    </div>

    <div id='fail_result_container'>
        <div>!</div>
        <div id='fail_result_message'></div>
        <div id='close_fail_btn'>&#215;</div>
    </div>

    <span id='maximize_btn'>Show Preview</span>
</div>


</div>

{% endblock %}

courses/templates/courses/course_index.html
{% extends "base.html" %}

{% block title %}Course list{% endblock %}


{% block extra_script_link %}
{% load staticfiles %}
<script type='text/javascript' src='{% static "courses/course_index.js" %}'>
</script>
<link type='text/css' rel='stylesheet' href='{% static "courses/course_index.css" %}' />
{% endblock %}

{% block page_title %}Course List{% endblock %}
{% block body %}
<p class='main_text'>Currently, we are offering the following Course. You can start to try one of them. Enjoy!</p>
{% for key, course in course_list.items %}
<div class='course_wrapper' 
    data-url='{% url "courses:lesson_index" course.slug %}'>
    <h2>{{ course.title }}</h2>
    <p>{{ course.short_description }}</p>
    {% if course.completed %}
    <p> woo lalala </p>
    {% endif %}
</div>
{% endfor %}
{% endblock %}

courses/templates/courses/end_of_course.html
{% extends 'base.html' %}

{% block h1 %}End of Course{% endblock %}

{% block extra_script_link %}
{% load staticfiles %}
<script type='text/javascript' src='{% static 'courses/end_of_course.js' %}'></script>
<link rel='stylesheet' type='text/css' href='{% static 'courses/end_of_course.css' %}'></link>
{% endblock %}

{% block body %}

<p>{{ course.summary }}</p>

<a href='{% url "courses:course_index" %}'>Go back to course index</a>

{% endblock %}

courses/templates/courses/lesson.html
{% extends 'base_2.html' %}

{% block extra_script_link %}
{% load staticfiles %}
<link rel='stylesheet' type='text/css' 
href='{% static 'courses/lesson.css' %}' />
<script type='text/javascript' 
    src='{% static "courses/lesson.js" %}'></script>
{% endblock %}

{% block body %}
    <img id='expand_btn' height='' width='' 
    src='{% static "strip_button.gif" %}' alt='expand button' />

<div id='top_left_wrapper'>
    <div id='nav_wrapper'>
        <nav>
        <h3>MENU</h3>
        <a class='links' href='{% url "courses:course_index" %}'>
            <div class='link_div'>COURSES</div></a>
        <a class='links' href='{% url "courses:lesson_index" course.slug %}'>
            <div class='link_div'>LESSONS</div></a>

        {% if user.username %}
        <a class='links' href='{% url "patio:dashboard" %}'>
            <div class='link_div'>DASHBOARD</div></a>
        <a class='links' href='{% url "patio:logout" %}'>
            <div class='link_div'>LOGOUT</div></a>
        {% else %}
        <a class='links' ><div class='link_div'
                data-url='{% url "patio:login" %}'>LOGIN</div></a>
        <a class='links' ><div class='link_div' 
                data-url='{% url "patio:registration" %}'>
                REGISTER AN ACCOUNT</div></a>
        {% endif %}
        </nav>
    </div>
</div>

    <div id='center_div'>
        <header><h1>{{ lesson.title }}</h1></header>
        <p class='main_text'>{{ lesson.description }}</p>
        <a id='left_button'
            href='{% url "courses:lesson_index" course.slug %}'>
            Back to Lesson list</a>

        <div id='video_wrapper'>
        <iframe width="100%" height="300" src='{{ lesson.video_link }}' frameborder="0" allowfullscreen></iframe>
        </div>

        <a id='right_button'
            href='{% url "courses:challenge" course.slug lesson.no 1 %}'>
            Move on to Challenge 1</a>
    </div>
</div>
{% endblock %}

courses/templates/courses/lesson_index.html
{% extends "base.html" %}

{% block extra_script_link %}
{% load staticfiles %}
<script type='text/javascript' src='{% static "courses/lesson_index.js" %}'>
</script>
<link type='text/css' rel='stylesheet' 
href='{% static "courses/lesson_index.css" %}' />
{% endblock %}

{% block page_title %}Lesson list{% endblock %}

{% block body %}
<p class='main_text'>Currently, we are offering the following {{ course.title }}  lessons. Watch the video, try the challenges!<p>
<h2>Click to view video for individual lessons or click on the challenges to try them out directly</h2>
{% for key, lesson in lesson_list.items %}
<div class='lesson_wrapper'
    data-url='{% url "courses:lesson" course lesson.no %}'>
    <h2>{{ lesson.title }}</h2>
    <p>{{ lesson.description }}</p>
    <!--    <div class='video_wrapper'></div>--!>
    <div class='challenge_wrapper'>
        <ul>
            {% for key, challenge in lesson.challenges.items %}
            {% if challenge.completed %}
            <li>
            <a class='completed' href='{% url "courses:challenge" course lesson.no challenge.no %}'>{{ challenge.title }}</a> &#10003;

            {% else %}
            <li>
            <a class='incomplete' href='{% url "courses:challenge" course lesson.no challenge.no %}'>{{ challenge.title }}</a>
            {% endif %}
            </li>
            {% endfor %}
        </ol>
    </div>
</div>
{% endfor %}
{% endblock %}

courses/templates/courses/success_snippet.html
{{ message }}
<span id='success_btn' data-url='{{ next_url }}'>{{ button_val }}</span>
{% load staticfiles %}
<script type='text/javascript' src='{% static "courses/success_snippet.js" %}'>
</script>