basal/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView
from . import views

urlpatterns = patterns('',
    url(r'^$', views.MainView.as_view(), name='main'), 
    url(r'^about_us/$', 
        TemplateView.as_view(template_name="basal/aboutus.html"),
        name='about_us'),
    url(r'^registration/$', views.RegistrationView.as_view(), 
        name='registration'),
    url(r'^login/$', 
        'django.contrib.auth.views.login', {
            'template_name': 'basal/login.html'},
        name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', {
            'template_name': 'basal/password_reset.html',
            'email_template_name': 'basal/password_reset_email.html',
            'post_reset_redirect': '/courses/'}, 
        name='password_reset'),
    url(r'^password_reset_confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 
        'django.contrib.auth.views.password_reset_confirm', {
            'template_name': 'basal/password_reset_confirm.html',
            'post_reset_redirect': '/courses/'},
        name='password_reset_confirm'),
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'), 
    url(r'^dashboard/password_change/$', 
        'django.contrib.auth.views.password_change', {
            'template_name': 'basal/password_change.html',
            'post_change_redirect': '/dashboard/'},
        name='password_change'),
    url(r'^dashboard/profile_update/$', views.ProfileUpdateView.as_view(),
        name='profile_update'),
)

script_cafe/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('basal.urls', namespace='basal')), 
    url(r'^admin/', include(admin.site.urls)),
    url(r'^courses/', include('courses.urls', 
        namespace='courses')),
)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang='en'>
    <head>
        <meta charset='utf-8'>
        <meta content='width=985, initial-scale=0.75, maximum-scale=1.0' name='viewport'>
        <meta name='description' content=''>
        <meta name='author' content=''>  
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
        <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <div id='popup_container'>
        <img id='close_btn' height='19' width='19' 
        src='{% static "close_btn.gif" %}' alt='close button' />
        <div id='popup_content'></div>
    </div>
    <div id='popup_screen'></div>

    <div id='wrapper'>
        <div id='header'>
            <span id='site_title'>Script Café</span>
            <img id="image" src='{% static "img/coffee.png" %}' height="50" width="50"/>
            <nav>
            {% if user.username %}
            <p class='current_user'>Hi {{ user.username }} :)</p>
            <a class='links' href='{% url "courses:course_index" %}'>
                <span>COURSES</span></a>

            <a class='links' href='{% url "basal:dashboard" %}'>
                <span>DASHBOARD</span></a>
            <a class='links' href='{% url "basal:logout" %}'>
                <span>LOGOUT</span></a>
            {% else %}
            <p class='current_user'>Welcome to Script Café</p>
            <a class='links' ><span id='sign_in_button' 
                    data-url='{% url "basal:login" %}'>LOGIN</span></a>
            <a class='links' ><span id='create_an_account_button' 
                    data-url='{% url "basal:registration" %}'>
                    REGISTER AN ACCOUNT</span></a>
            {% endif %}
            </nav>
        </div>

        <div id='body'>
            <header><h1>{% block page_title %}{% endblock %}</h1></header>

            {% block body %}
            {% endblock %}	
        </div>

        <div id="footer">
            <div id='footer_1'>
                <ul>
                    <li><a id='courses' 
                        href='{% url "basal:about_us" %}'>About Us</a></li>
                    <li>Copyright &copy; 2013 Script Café</li>
                </ul>
            </div>

            <div id='footer_2'>
                <ul>
                    <li><div id='twitter_btn'>
                    <a href="https://twitter.com/share" 
                       class="twitter-share-button" 
                       data-url="http://cmpt470.csil.sfu.ca:8013/school" 
                       data-text="Script Cafe - Let technology be your friend">
                       Tweet</a></div></li>				
                    <li><div id='fb_btn' class="fb-share-button" 
                       data-href="http://cmpt470.csil.sfu.ca:8013/school" 
                       data-width="59" data-type="box_count"></div></li>
                </ul>
            </div>

            <div id='footer_3'>
                <ul>
                    {% if user.username %}
                    <li><a href='{% url "courses:course_index" %}'>
                        Courses</a></li>
                    <li><a href='{% url "basal:dashboard" %}'>
                        Dashboard</a></li>
                    <li><a href='{% url "basal:logout" %}'>
                        Logout</a></li>

                        {% else %}
                        <li><a href='{% url "basal:login" %}'>
                            Login</a></li>
                        <li><a href='{% url "basal:registration" %}'>
                            Register and account</a></li>
                        {% endif %}
                    </ul>
                </div>

            </div>

            <link rel='stylesheet' type='text/css' 
            href='{% static 'base.css' %}' />
            <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
            <link href='http://fonts.googleapis.com/css?family=Ribeye|Chela+One|Lily+Script+One|Finger+Paint' rel='stylesheet' type='text/css'>
            <script type='text/javascript' 
                src='{% static "jquery-1.10.2.min.js" %}'></script>
            <script type='text/javascript'
                src='{% static "jquery-ui-1.10.3.custom.js" %}'></script>
            <script type='text/javascript' 
                src='{% static 'base.js' %}'></script>
            <script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" 
                type="text/javascript"></script>

            {% block extra_script_link %}{% endblock %}
        </body>
    </html>

templates/base_2.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang='en'>
    <head>
        <meta charset='utf-8'>
        <meta content='width=985, initial-scale=0.75, maximum-scale=1.0' 
            name='viewport'>
        <meta name='description' content=''>
        <meta name='author' content=''>  
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>
        <div id='body'>
            {% block body %}{% endblock %}	
        </div>

        <link rel='stylesheet' type='text/css' 
        href='{% static 'base_2.css' %}' />
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
        <script type='text/javascript' 
            src='{% static "jquery-1.10.2.min.js" %}'></script>
        <script type='text/javascript'
            src='{% static "jquery-ui-1.10.3.custom.js" %}'></script>
        <script type='text/javascript' 
            src='{% static 'base_2.js' %}'></script>
        <script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" 
            type="text/javascript"></script>

        {% block extra_script_link %}{% endblock %}
    </body>
</html>

templates/popup_form.html
<header>
<h2 id='popup_title'>{% block popup_title %}{% endblock %}</h2>
</header>

<div id='popup_body'>
    {% block body %}{% endblock %}
</div>

{% load staticfiles %}
<script type='text/javascript' src='{% static 'jquery-1.10.2.min.js' %}'>
</script>
<link rel='stylesheet' type='text/css' href='{% static 'popup_form.css' %}' />
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' 
rel='stylesheet' type='text/css'>

{% block extra_script_link %}{% endblock %}