basal/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView
from . import views

urlpatterns = patterns('',
    url(r'^$', views.MainView.as_view(), name='main'), 
    url(r'^about_us/$', 
        TemplateView.as_view(template_name="basal/aboutus.html"),
        name='about_us'),
    url(r'^registration/$', views.RegistrationView.as_view(), 
        name='registration'),
    url(r'^login/$', 
        'django.contrib.auth.views.login', {
            'template_name': 'basal/login.html'},
        name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', {
            'template_name': 'basal/password_reset.html',
            'email_template_name': 'basal/password_reset_email.html',
            'post_reset_redirect': '/courses/'}, 
        name='password_reset'),
    url(r'^password_reset_confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 
        'django.contrib.auth.views.password_reset_confirm', {
            'template_name': 'basal/password_reset_confirm.html',
            'post_reset_redirect': '/courses/'},
        name='password_reset_confirm'),
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'), 
    url(r'^dashboard/password_change/$', 
        'django.contrib.auth.views.password_change', {
            'template_name': 'basal/password_change.html',
            'post_change_redirect': '/dashboard/'},
        name='password_change'),
    url(r'^dashboard/profile_update/$', views.ProfileUpdateView.as_view(),
        name='profile_update'),
)

script_cafe/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('basal.urls', namespace='basal')), 
    url(r'^admin/', include(admin.site.urls)),
    url(r'^courses/', include('courses.urls', 
        namespace='courses')),
)

basal/models.py
import datetime
from django.db import models
from courses.models import Challenge, Course
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    about_me = models.TextField()
    location = models.CharField(max_length=50)
    last_challenge = models.ForeignKey(Challenge, null=True, blank=True)

    def get_last_challenge(self):
        try:
            self.last_challenge
        except (NameError, ObjectDoesNotExist):
            return None
        else:
            return self.last_challenge

    def get_challenges_completed_day(self):
        temp = ChallengeProgress.objects.filter(user_id=self.user)
        return temp.filter(completed_date=timezone.now()).count()

    def new_user(self):
        if self.get_last_challenge() is None:
            return True
        else:
            return False

    def get_challenges_completed_week(self):
        date_temp = timezone.now() - datetime.timedelta(days=6)
        temp = ChallengeProgress.objects.filter(user_id=self.user)
        temp = temp.filter(completed_date__gt=date_temp)
        return temp.filter(completed_date=timezone.now()).count()

    def get_all_completed_challenges(self, slug):
        temp = ChallengeProgress.objects.filter(user_id=self.user)
        temp = temp.filter(challenge_id__lesson_id__course_id__slug=slug)
        return temp.filter(completed_date__lte=timezone.now())

    def completed_course(self, slug):
        temp = self.get_all_completed_challenges(slug).count()
        return temp == Course.objects.get(slug=slug).get_total_challenges()

    def completed_challenge(self, challenge_id):
#        import pdb;pdb.set_trace()
        try:
            ChallengeProgress.objects.filter(user_id=self.user)
        except (NameError, ObjectDoesNotExist):
            return False
        else:
            temp = ChallengeProgress.objects.filter(user_id=self.user)
        
        try:
            temp.get(challenge_id=challenge_id)
        except (NameError, ObjectDoesNotExist):
            return False
        else:
            return temp.get(challenge_id=challenge_id).was_completed()

    def new_user(self):
        try:
            temp = ChallengeProgress.objects.filter(user_id=self.user)
        except (ObjectDoesNotExist):
            return True
        else:
            if temp.count() == 0: 
                return True
            else:
                return False

class ChallengeProgress(models.Model):
    challenge_id = models.ForeignKey(Challenge)
    user_id = models.ForeignKey(User)
    snippet = models.TextField()
    completed_date = models.DateField(null=True, blank=True)
    
    def __unicode__(self):
        return '[Challenge Progress of %s] for %s' %  (
                self.user_id, self.challenge_id)

    def was_completed(self):
        try:
            self.completed_date
        except NameError:
            return False
        else:
            if self.completed_date is None:
                return False
            else:
                return True

    was_completed.admin_order_field = 'completed_date'
    was_completed.boolen = True
    was_completed.short_description = 'Completed?'

basal/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class UserRegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

basal/views.py
from django.views import generic
from django.contrib.auth.models import User
from courses.models import *
from .forms import *
from basal.models import *
from django.contrib.auth.forms import *
from django.contrib.auth import login, logout, get_user_model
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseServerError
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import password_reset
from django.shortcuts import render

class MainView(generic.FormView):
    form_class = AuthenticationForm
    template_name = 'basal/main.html'

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated():
            return HttpResponseRedirect(reverse('basal:dashboard'))
        else:
            form_class = self.get_form_class()
            form = self.get_form(form_class)
            return self.render_to_response(self.get_context_data(form=form))

class RegistrationView(generic.FormView):
    template_name = 'basal/registration.html'
    form_class = UserCreationForm

    def form_valid(self, form):
        user = form.save()
        new_user_profile = UserProfile(user=user,about_me='',location='') 
#        import pdb;pdb.set_trace()
        new_user_profile.save()

        messages.success(self.request, 
                'Registraion success! Welcome to coding ABC.')
        new_user = authenticate(username=self.request.POST['username'],
                                password=self.request.POST['password1'])
        login(self.request, new_user)
    
        return HttpResponseRedirect(reverse('basal:main'))

class DashboardView(generic.TemplateView):
    template_name = 'basal/dashboard.html'
    
    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
#        import pdb;pdb.set_trace()
        user = UserProfile.objects.get(user=self.request.user.id)

        context['userprofile'] = user 
        html_total = Course.objects.get(slug='html').get_total_challenges()
        css_total = Course.objects.get(slug='css').get_total_challenges()

        context['progress'] = { 
            'html_progress': user.get_all_completed_challenges('html').count(),
            'html_total': html_total, 
            'css_progress': user.get_all_completed_challenges('css').count(),
            'css_total': css_total
        }
        if user.get_last_challenge() is None:
            context['display_last_challenge'] = False
        else:
            context['display_last_challenge'] = True
            context['last_challenge'] = user.get_last_challenge()

        context['completed_day'] = user.get_challenges_completed_day()
        context['completed_week'] = user.get_challenges_completed_week()

        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DashboardView, self).dispatch(*args, **kwargs)

class ProfileUpdateView(generic.UpdateView):
    model = User
    form_class = UserForm
    template_name = 'basal/profile_update.html'

    def get_success_url(self):
        messages.success(self.request, 'profile updated successfully')
        return reverse('basal:main')

    def get_object(self):
        obj = User.objects.get(id=self.request.user.id)
        return obj

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProfileUpdateView, self).dispatch(*args, **kwargs)

def logout_view(request):
    logout(request)
#    messages.success(request, 'logout successfully')
    return HttpResponseRedirect(reverse('basal:main'))

basal/templates/basal/aboutus.html
{% extends 'base.html' %}

{% block title %}About Us{% endblock %}

{% block extra_script_link %}
{% load staticfiles %}
<script type='text/javascript' src='{% static 'basal/aboutus.js' %}'>
</script>
<link rel='stylesheet' type='text/css' href='{% static 'basal/aboutus.css' %}'></link>
{% endblock %}

{% block page_title %}About Us{% endblock %}

{% block body %}
<h3>Our Team Members: </h3>
<div>
<ul class="member">
	<li>Sean Su</li>
	<li>Henry Lam</li>
	<li>Na Han</li>
</ul>
</div>
{% endblock %}

basal/templates/basal/dashboard.html
{% extends 'base.html' %}

{% block page_title %}Dashboard{% endblock %}

{% block extra_script_link %}
{% load staticfiles %}
<script type='text/javascript' src='{% static "basal/dashboard.js" %}'></script>
<script type="text/javascript" src='{% static "basal/dist/jquery.jqplot.min.js" %}'></script>
<script type="text/javascript" src='{% static "basal/dist/plugins/jqplot.pieRenderer.min.js" %}'></script>
<script type="text/javascript" src='{% static "basal/dist/plugins/jqplot.donutRenderer.min.js" %}'></script>
<link type='text/css' rel='stylesheet' href='{% static "basal/dashboard.css" %}' />
<link type='text/css' rel='stylesheet' href='{% static "basal/dist/jquery.jqplot.css" %}' />
{% endblock %}

{% block body %}
<section id='profile'>
<header><h2>Profile</h2></header>
<p><strong>About Me:</strong> {{ userprofile.about_me }} </p>
<p><strong>Location:</strong> {{ userprofile.location }} </p>
<ul id='profile_list'>
    <li><strong>Username: </strong>{{ user.username }}</li>
    <li><strong>First Name: </strong>{{ user.first_name }}</li>
    <li><strong>Last Name: </strong>{{ user.last_name }}</li>
    <li><strong>Email: </strong>{{ user.email }}</li>
    <li><strong>Last Login: </strong>{{ user.last_login }}</li>
</ul>
<p>A student since {{ user.date_joined }}</p>
<div id='profile_edit_options'>
    <span><a id='change_password_button' 
            href='#changePassword' data-url='{% url "basal:password_change" %}' 
            onclick='get_password_change_form()')>change password</a></span>

    <span><a id='update_profile_button' 
            href='#updateProfile' data-url='{% url "basal:profile_update" %}' 
            onclick='get_profile_update_form()')>update profile</a></span>
</div>
</section>

<section id='course_progress'>
<header><h2>Course Progress</h2></header>
<ul id='course_progress_list'>
    <li id="htmlProgress"><strong>HTML</strong>
    <p><span id="html_completed">{{ progress.html_progress }}</span> out of 
    <span id="html_total">{{ progress.html_total }}</span> have been completed.
    <p><span>
        <a href='{% url "courses:lesson_index" "html" %}'>
            <strong> Here to continue..</strong>
        </a>
    </span></p>
	</p>
	<div id="chart1" style="width:200px;height:200px"></div>
	</li>
	
	<li id="cssProgress"><strong>CSS</strong>
    <p><span id="css_completed">{{ progress.css_progress }}</span> out of 
    <span id="css_total">{{ progress.css_total }}</span> have been completed.
    <p><span>
        <a href='{% url "courses:lesson_index" "css" %}'>
            <strong> Here to continue..</strong>
        </a>
    </span></p>
	</p>
	<div id="chart2" style="width:200px;height:200px"></div>
	</li>
</ul>
</section>

<section id='activities'>
<header><h2>Activities</h2></header>
{% if display_last_challenge %}
<p><strong>Last challenge: </strong>{{ last_challenge.title }} 
<a href='{% url "courses:challenge" last_challenge.course_id.slug last_challenge.id %}'>continue</a></p>
{% else %}
<p><strong>Last Challenge: </strong>No challenges attempted so far.
{% endif %}

<p><strong> {{ completed_day }} </strong> Challenges Completed Today!</p>
<p><strong> {{ completed_week }} </strong> Challenges Completed This Week!</p>
</section>
{% endblock %}

basal/templates/basal/login.html
{% extends 'popup_form.html' %}

{% block extra_script_link %}
{% load staticfiles %}
<link rel='stylesheet' type='text/css' 
href='{% static "basal/login.css" %}' />
{% endblock %}

{% block popup_title %}Login{% endblock %}

{% block body %}
<div id='form_container'>
{% if form.non_field_errors %}
    <ul class='form-errors'>
        {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
        {% endfor %}
    </ul>
{% endif %}
	<form id='form' method='post' action='{% url "basal:login" %}'>
		{% csrf_token %}
		{% for field in form %}
        <div class='field_wrapper'>
            <div id="labelname">{{ field.label_tag }}</div>
            <div id="error"><strong>{{ field.errors }}</strong><div>
            <div id="field">{{ field }}</div>
            <p>{{ field.help_text }}</p>
        </div>
        {% endfor %}
        <input id="button" type='submit'/>
	</form>
</div>
{% endblock %}

basal/templates/basal/main.html
{% extends 'base.html' %}

{% block title %}Welcome to Script Café --- an online web development study platform{% endblock %}

{% block extra_script_link %}
{% load staticfiles %}
<script type='text/javascript' src='{% static 'basal/main.js' %}'>
</script>
<link rel='stylesheet' type='text/css' href='{% static 'basal/main.css' %}'>
</link>
{% endblock %}

{% block page_title %}Main Page{% endblock %}

{% block body %}
<div id="left">
	<p id="p1"><i>Welcome to <strong>Script Café</strong> --- an online web development study platform.</i></p>
	<p id="p2">You will have a journey to learn how to code interactively for <strong>FREE</strong>!</p>
	<p id="p3">Wanna create a website like the one on the right-hand side? </p>
	<p>Are you a member of Script Café? If not, join us <strong>NOW</strong> by creating your personal account.</p>
</div>
{% endblock %}

basal/templates/basal/password_change.html
{% extends 'popup_form.html' %}

{% block extra_script_link %}
{% load staticfiles %}
<link rel='stylesheet' type='text/css' href='{% static "basal/password_change.css" %}' />
{% endblock %}

{% block popup_title %}Password Change{% endblock %}

{% block body %}

	<form id='form' method='post' action='{% url "basal:password_change" %}'>
		{% csrf_token %}
		<div id='form_container'>
		<div id="lab">
		<p><ul id="lab_ul">
			<li id="oldlabel">{{ form.old_password.label }}</li>
			<li id="newlabel1">{{ form.new_password1.label }}</li>
			<li id="newlabel2">{{ form.new_password2.label }}</li>
		</ul></p>
		</div>
		<div id="pwd">
		<ul id="lab_ul">
			<li>{{ form.old_password }}</li>
			<li>{{ form.new_password1 }}</li>
			<li>{{ form.new_password2 }}</li>
		</ul>
		</div>
		<div id="msg">
		<ul>
			<li><strong>{{ form.old_password.errors }}</strong></li>
			<li><strong>{{ form.new_password1.errors }}</strong></li>
			<li><strong>{{ form.new_password2.errors }}</strong></li>
		</ul>
		</div>
		<input id="button" type='submit'/>
		</div>
	</form>

{% endblock %}

basal/templates/basal/password_reset.html
{% extends 'popup_form.html' %}

{% block extra_script_link %}
{% load staticfiles %}
<link rel='stylesheet' type='text/css' 
href='{% static "basal/login.css" %}' />
{% endblock %}

{% block popup_title %}Login{% endblock %}

{% block body %}
<div id='form_container'>
    <form id='form' method='post' action='{% url "basal:password_reset" %}'>
        {% csrf_token %}
        <div class='field_wrapper'>
            <label for='email_field'>Email</label>
            <input id='email_field' type='email' name='email' />
            <p>You will receive a link to create a new password via your 
            email.</p>
        </div>
        <input  type='submit'/>
        <a href='{% url "basal:password_reset" %}'>forgot password?</a>
    </form>
</div>
{% endblock %}

basal/templates/basal/profile_update.html
{% extends 'popup_form.html' %}

{% block extra_script_link %}
    {% load staticfiles %}
    <script type='text/javascript' src='{% static 'basal/profile_update.js' %}'></script>
	<link rel='stylesheet' type='text/css' href='{% static "basal/profile_update.css" %}' />
{% endblock %}

{% block popup_title %}Profile Update{% endblock %}
{% block body %}
<div id='form_container'>
	<form id='form' method='post' action='{% url "basal:profile_update" %}'>
		{% csrf_token %}
		{% for field in form %}
        <div class='field_wrapper'>
            <div id="labelname">{{ field.label_tag }}</div>
            <div id="error"><strong>{{ field.errors }}</strong><div>
            <div id="field">{{ field }}</div>
            <p>{{ field.help_text }}</p>
        </div>
        {% endfor %}
        <input id="button" type='submit'/>
	</form>
</div>
{% endblock %}

basal/templates/basal/registration.html
{% extends 'popup_form.html' %}
{% block extra_script_link %}
{% load staticfiles %}
<link rel='stylesheet' type='text/css' href='{% static "basal/registration.css" %}' />
{% endblock %}

{% block popup_title %}Registration{% endblock %}

{% block body %}
<div id='form_container'>
	<form id='form' method='post' action='{% url "basal:registration" %}'>
		{% csrf_token %}
		{% for field in form %}
        <div class='field_wrapper'>
            <div id="labelname">{{ field.label_tag }}</div>
            <div id="error"><strong>{{ field.errors }}</strong><div>
            <div id="field">{{ field }}</div>
            <p>{{ field.help_text }}</p>
        </div>
        {% endfor %}
        <input id="button" type='submit'/>
	</form>
</div>
{% endblock %}





<!--
<div id='form_container'>
	<form id='form' method='post' action='{% url "basal:registration" %}'>
		{% csrf_token %}
		{% for field in form %}
        <div class='field_wrapper'>
            <div>{{ field.label_tag }}</div>
            <div>{{ field.errors }}<div>
            <div>{{ field }}</div>
            <p>{{ field.help_text }}</p>
        </div>
        {% endfor %}
        <input id="button" type='submit'/>
	</form>
</div> -->